apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    app: fortune
spec:
  containers:
    - name: web-server
      image: nginx:latest
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
    - name: git-sync
      image: openweb/git-sync:0.0.1
      env:
        - name: GIT_SYNC_REPO
          value: 'https://github.com/nkavtur/kubia-website-example'
        - name: GIT_SYNC_DEST
          value: '/var/htdocs'
        - name: GIT_SYNC_BRANCH
          value: 'master'
        - name: GIT_SYNC_REV
          value: 'FETCH_HEAD'
        - name: GIT_SYNC_WAIT
          value: '10'
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
  volumes:
    - name: html
      emptyDir:
        medium: Memory